# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v1/val_data_joint.npy
  label_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v1/val_label.pkl
  debug: False

# model
model: model.zoom_transformer.Model
model_args:
  num_class: 14
  num_person: 2
  num_point: 17
  num_head: 6
  in_channels: 3
  graph: graph.volleyball.AdjMatrixGraph
  graph_args:
    labeling_mode: 'spatial'


# test 
phase: test
device: [ 5 ]
test_batch_size: 64
weights: ./runs/60-epoch/ZT_V-SA-49-20750.pt

work_dir: ./work_dir
model_saved_name: ./work_dir/model_vsa
save_score: True