work_dir: ./work_dir/ZT_V-SA
model_saved_name: ./runs/ZT_V-SA

# feeder
feeder: feeders.feeder.Feeder
num_worker: 32
train_feeder_args:
  data_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v1/2024-5-5/train_data_joint.npy
  label_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v1/2024-5-5/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v1/2024-5-5/val_data_joint.npy
  label_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v1/2024-5-5/val_label.pkl
  normalization: False

# model
model: model.zoom_transformer_fixed_link.Model
model_args:
  num_class: 14
  num_person: 1
  num_point: 17
  num_head: 6
  in_channels: 3
  graph: graph.pingpong.AdjMatrixGraph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0005
base_lr: 0.1
step: [ 30, 40, 50 ]

# training
device: [ 0,1,2,3,4,5 ]
batch_size: 64
test_batch_size: 64
num_epoch: 60
nesterov: True
warm_up_epoch: 2