work_dir: ./work_dir/p2a
model_saved_name: myModel

# feeder
feeder: feeders.feeder.Feeder
num_worker: 8
train_feeder_args:
  data_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v1/2024-5-5/train_data_joint.npy
  label_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v1/2024-5-5/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v1/2024-5-5/val_data_joint.npy
  label_path: ../dataset/2024-p2a/2s-AGCN+MSG3D-fomat/p2a/v1/2024-5-5/val_label.pkl
  normalization: False

# model
model: model.zoom_angular_transformer.Model
model_args:
  num_class: 14
  num_person: 1
  num_point: 17
  num_head: 6
  in_channels: 12
  graph: graph.volleyball.AdjMatrixGraph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0005
base_lr: 0.01 # org 0.1
step: [ 40,50,60 ]

# training
device: [ 0 ]
batch_size: 64
test_batch_size: 64
num_epoch: 70
nesterov: True
warm_up_epoch: 2

# test
save_score: True